mongo:
  connectionString   : 'mongodb://localhost:27017/keentour_new'
logging:
    File :
      filename: "keentour.log"
      maxsize: 10485760,
      max_files: 3
      json: true
      level : error
    Console:
      level : info




