mongo:
  connectionString   : 'mongodb://nodejitsu:4c561790ec3d4b1346c9830388a2aa6d@alex.mongohq.com:10056/nodejitsudb56760335096'
host : 'http://www.keentour.com'
logging:
    File :
      filename: "public/logs/keentour.log"
      maxsize: 10485760,
      max_files: 3
      json: true
      level : warn
      handleExceptions: true
    Console:
      level : info
