mongo:
  connectionString   : 'mongodb://localhost:27017/keentour_new'
host : 'http://www.keentour.com'
logging:
    File :
      filename: "public/logs/keentour.log"
      maxsize: 10485760,
      max_files: 3
      json: true
      level : warn
      handleExceptions: true
    Console:
      level : info
